-
  codes:
    - 0
    - 1
    - 2
  icon: "tornado"
-
  codes:
    - 3
    - 4
  icon: "storm-showers"
-
  codes:
    - 5
    - 6
    - 7
    - 8
  icon: "snow-wind"
-
  codes:
    - 9
    - 10
    - 11
    - 12
  icon: "showers"
-
  codes:
    - 13
    - 14
    - 15
    - 16
  icon: "snowflake-cold"
-
  codes:
    - 17
    - 18
    - 19
  icon: "hail"
-
  codes:
    - 20
    - 21
    - 22
  icon: "fog"
-
  codes:
    - 23
    - 24
  icon: "strong-wind"
-
  codes:
    - 25
  icon: "thermometer-exterior"
-
  codes:
    - 26
    - 27
    - 28
    - 29
    - 30
  icon: "cloudy"
-
  codes:
    - 31
  icon: "night-clear"
-
  codes:
    - 32
    - 33
    - 34
  icon: "day-sunny"
-
  codes:
    - 35
  icon: "rain-mix"
-
  codes:
    - 36
  icon: "thermometer"
-
  codes:
    - 37
    - 38
    - 39
  icon: "thunderstorm"
-
  codes:
    - 40
  icon: "raindrops"
-
  codes:
    - 41
    - 42
    - 43
  icon: "snow"
-
  codes:
    - 44
  icon: "cloud"
-
  codes:
    - 45
    - 46
    - 47
  icon: "storm-showers"
